///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SpecialistModel {
/*
{
  "__typename": "User",
  "id": "668344af-ad83-40bb-915a-c7e69bccb6c2",
  "fullName": "Samuel Olusola",
  "emailAddress": "solathecoder@gmail.com",
  "phoneNumber": "+2348128921525"
}
*/

  String? Typename;
  String? id;
  String? fullName;
  String? emailAddress;
  String? phoneNumber;
  String? role;

  SpecialistModel({
    this.Typename,
    this.id,
    this.fullName,
    this.emailAddress,
    this.phoneNumber,
    this.role,
  });
  SpecialistModel.fromJson(Map<String, dynamic> json) {
    Typename = json["__typename"]?.toString();
    id = json["id"]?.toString();
    fullName = json["fullName"]?.toString();
    emailAddress = json["emailAddress"]?.toString();
    phoneNumber = json["phoneNumber"]?.toString();
    role = json['role']?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["__typename"] = Typename;
    data["id"] = id;
    data["fullName"] = fullName;
    data["emailAddress"] = emailAddress;
    data["phoneNumber"] = phoneNumber;
    data['role'] = role;
    return data;
  }
}
